/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import aluno.Aluno;
import fachada.Fachada;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import turma.Turma;

/**
 *
 * @author Luhan
 */
public class TurmaInserirAlunoTela extends javax.swing.JInternalFrame {

    /**
     * Creates new form TurmaInserirAlunoTela
     */
    Fachada fachada = new Fachada();
    DefaultTableModel modeloAluno = new DefaultTableModel(), modeloTurma = new DefaultTableModel();
    
    public TurmaInserirAlunoTela() {
        initComponents();
        modeloAluno.setColumnIdentifiers(new String[]{"Matrícula", "Nome"});
        jTableAluno.setModel(modeloAluno);
        modeloTurma.setColumnIdentifiers(new String[]{"Código", "Atividade", "Descrição"});
        jTableTurma.setModel(modeloTurma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodTurma = new classesBasicas.JTextFieldSomenteNumeros();
        jButtonPesquisarTurma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTurma = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMatAluno = new classesBasicas.JTextFieldSomenteNumeros();
        jButtonPesquisarAluno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();
        jButtonInserirAlunoTurma = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel3.setText("Cod Turma:");

        jButtonPesquisarTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        jButtonPesquisarTurma.setText("Pesquisar");
        jButtonPesquisarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarTurmaActionPerformed(evt);
            }
        });

        jTableTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableTurma);

        jLabel1.setText("Mat Aluno:");

        jTextFieldMatAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatAlunoActionPerformed(evt);
            }
        });

        jButtonPesquisarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        jButtonPesquisarAluno.setText("Pesquisar");
        jButtonPesquisarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarAlunoActionPerformed(evt);
            }
        });

        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableAluno);

        jButtonInserirAlunoTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jButtonInserirAlunoTurma.setText("Inserir");
        jButtonInserirAlunoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirAlunoTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonInserirAlunoTurma)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldMatAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPesquisarAluno))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldCodTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPesquisarTurma))))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonInserirAlunoTurma, jButtonPesquisarAluno, jButtonPesquisarTurma});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldCodTurma, jTextFieldMatAluno});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCodTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarTurma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarAluno)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButtonInserirAlunoTurma)
                .addGap(56, 56, 56))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonInserirAlunoTurma, jButtonPesquisarAluno, jButtonPesquisarTurma});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMatAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatAlunoActionPerformed

    private void jButtonInserirAlunoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirAlunoTurmaActionPerformed
        // TODO add your handling code here:
        try {
            //DADOS DA TURMA
            Turma turma = new Turma();
            turma.setCodigo(Integer.parseInt(jTextFieldCodTurma.getText()));
            turma.getAluno().setMatricula(Integer.parseInt(jTextFieldMatAluno.getText()));
            fachada.inserirAlunoTurma(turma);
            JOptionPane.showMessageDialog(rootPane, "Aluno cadastrado na turma com sucesso");
            //Limpar Campos preenchidos 
            jTextFieldCodTurma.setText("");
            jTextFieldMatAluno.setText("");
            modeloAluno.setRowCount(0);
            modeloTurma.setRowCount(0);
            jTextFieldCodTurma.requestFocus(); // Retornar para o início

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonInserirAlunoTurmaActionPerformed

        private void deleteRowsAluno() {
        while (modeloAluno.getRowCount() > 0) {
            modeloAluno.removeRow(0);
        }
    }

    private void deleteRowsTurma() {
        while (modeloTurma.getRowCount() > 0) {
            modeloTurma.removeRow(0);
        }
    }
    
    private void jButtonPesquisarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarTurmaActionPerformed
        // TODO add your handling code here:
        try {
            Turma turma = new Turma();
            //turma
            if (jTextFieldCodTurma.getText().trim().equals("") == false) {
                turma.setCodigo(Integer.parseInt(jTextFieldCodTurma.getText().trim()));
            }
            ArrayList<Turma> resposta = fachada.listarTurmaAtividade(turma);
            deleteRowsTurma();
            if (resposta.size() > 0) {
                for (Turma tur : resposta) {
                    modeloTurma.addRow(new String[]{tur.getCodigo() + "", tur.getAtividade().getCodigo() + "", tur.getAtividade().getDescricao()});
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Não existe resultados para turmas com o filtro desejado");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonPesquisarTurmaActionPerformed

    private void jButtonPesquisarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarAlunoActionPerformed
        // TODO add your handling code here:
        try {
            Turma turma = new Turma();
            //turma
            if (jTextFieldMatAluno.getText().trim().equals("") == false) {
                turma.getAluno().setMatricula(Integer.parseInt(jTextFieldMatAluno.getText().trim()));
            }
            ArrayList<Aluno> resposta = fachada.listarAlunos(turma);
            deleteRowsAluno();
            if (resposta.size() > 0) {
                for (Aluno alu : resposta) {
                    modeloAluno.addRow(new String[]{alu.getMatricula()+ "", alu.getNome()});
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Não existe resultados para alunos com o filtro desejado");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonPesquisarAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserirAlunoTurma;
    private javax.swing.JButton jButtonPesquisarAluno;
    private javax.swing.JButton jButtonPesquisarTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JTable jTableTurma;
    private javax.swing.JTextField jTextFieldCodTurma;
    private javax.swing.JTextField jTextFieldMatAluno;
    // End of variables declaration//GEN-END:variables
}
